
version: 2.1


jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

steps:
      - checkout
    
      - run:
          name: build dependencies
          command: bundle install
          
      - run: 
          name: bild the jekyll site
          command bundle exec jekyll build
    
      - run:
          name: "Say something"
          command: "echo Hello, something!"


      - run:
        name: Print the Current date and Time, qqq
        command: date
